Trying a new way

diff --git a/.github/workflows/ci-checks.yaml b/.github/workflows/ci-checks.yaml
--- a/.github/workflows/ci-checks.yaml
+++ b/.github/workflows/ci-checks.yaml
@@ -49,20 +49,20 @@ jobs:
       - name: Install dependencies
         run: poetry install
       - name: test
-        run: cd tests && pytest --tap-stream --cov-report=html --junitxml=junit.xml
-      - name: Upload Test report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: test-results
-          path: junit.xml
-          reporter: java-junit
-          fail-on-error: false
+        run: cd tests && poetry run pytest --html=report.html  
+      # - name: Upload Test report
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()
+      #   with:
+      #     name: test-results
+      #     path: junit.xml
+      #     reporter: java-junit
+      #     fail-on-error: false
       - name: upload-coverage-report
         uses: actions/upload-artifact@v2
         with:
           name: coverage-report
-          path: htmlcov/
+          path: "test_report/"
           if-no-files-found: warn
   flake8:
     runs-on: ubuntu-latest
